replicaCount: 1

image:
  repository: docker.io/fredsheppard/true_wind
  tag: latest
  pullPolicy: IfNotPresent

port: 5000

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
