replicaCount: 1

debug: true

image:
  repository: 708726711781.dkr.ecr.us-east-1.amazonaws.com/flask-app
  tag: latest
  pullPolicy: Always

containerPort: 5000

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
