replicaCount: 1

debug: true

image:
  repository: docker.io/fredsheppard/true_wind
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi