replicaCount: 1

image:
  repository: 708726711781.dkr.ecr.us-east-1.amazonaws.com/flask-app
  tag: echo
  pullPolicy: Always

containerPort: 5000

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
